inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rake.yml
    - lib/rubocop.rspec.yml

AllCops:
  TargetRubyVersion: 3.0.0
  NewCops: enable
  Include:
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - smart_injection.gemspec
    - bin/console

# NOTE: It is not suitable for infrastracture-level frameworks
Metrics/ParameterLists:
  Enabled: false
